modLoader="javafml"
loaderVersion="[28,)"
license="MIT"
issueTrackerURL="https://github.com/Virtuoel/Statement/issues"
[[mods]]
modId="statement"
version="${version}"
displayName="Statement"
displayURL="https://www.curseforge.com/minecraft/mc-mods/statement/"
logoFile="statement_icon.png"
authors="Virtuoel"
description='''
Library to assist with adding properties to existing block states.
'''
